export const contacts = ["Awadhesh Chaurasia",
    "Banarsi Prasad Chaurasia",
    "Aditya Chaurasia",
    "Anuradha Chaurasia",
    "Ritu Chaurasia",
    "Saurabh Mauraya",
    "Gaurav Chaurasia",
    "Hariom Maurya",
    "Rajat Verma",
    "Aarti Chaurasia",
    "Vipul Trivedi",
    "Rishi Jaiswal",
    "Rinkesh jaiswal",
    "Amit Singh",
    "Vaishali Chauhan",
    "Anamika Gupta",
    "Dr. Shruti Chauhan",
    "Sheetal Verma",
    "Kush Prakash",
    "Shubham Singh",
    "Shivanshu Srivastava",
    "Shashank Tiwari",
    "Ankit Srivastava",
    "Anushka Sinha",
    "Shivang Srivastava",
    "Akash Pratap",
    "Ashish Singh",
    "Priyanshu",
    "Khushboo Gupta",
    "Vinay Vishvakrma",
    "Rahul Singh",
    "Chandan Yadav",
    "Shobhit Chaurasia",
    "Senhi Chaurasia",
    "Naya",
"Kabir",
"Ishaan",
"Jai",
"Inaya",
"Amar",
"Dhruv",
"Kanan",
"Diya",
"Shyla",
"Agastya",
"Ananya",
"Sana",
"Nila",
"Tamia",
"Shaan",
"Ajay",
"Jaya",
"Anjali",
"Aditi",
];