export const watchcontent = [
    {
        name: "Imagine Dragons",
        logo: "https://upload.wikimedia.org/wikipedia/en/b/b5/ImagineDragonsEvolve.jpg",
        date: " Mar 7, 2017 ",
        caption: "Believer Song",
        vedio: "https://www.youtube.com/embed/7wtfhZwyrcc",
        comment: "Nice",
    },
    {
        name: "Sony Music Entertainment India",
        logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Sony-Music-Logo.svg/1200px-Sony-Music-Logo.svg.png",
        date: " Oct 27, 2015 ",
        caption: "Song Name - Luka Chuppi Movie - Rang De Basanti Singer - A.R. Rahman & Lata Mangeshkar Composer - A.R. Rahman Lyricists - Prasoon Joshi & Nacim",
        vedio: "https://www.youtube.com/embed/FFpgYjL2aJo",
        comment: "WOW",
    },
    {
        name: "The Viral Fever",
        logo: "https://yt3.ggpht.com/ytc/AKedOLSMKxpcCRD_mO-B01VxY5JUSpoDYLDzrPL_2jSe5w=s900-c-k-c0x00ffffff-no-rj",
        date: "Jul 1, 2022",
        caption: "Brahmastra: Leaked Audition Tape ft. Amitabh, Salman, Aamir & Sanju Baba | TVF",
        vedio: "https://www.youtube.com/embed/tpDG5HS3M9o",
        comment: "",
    },
    {name:"Brut India",
    logo:"https://yt3.ggpht.com/ytc/AKedOLTELAeNDZzdhklEF6cLVfhCeTeQCRzvaWlyLpHJaw=s900-c-k-c0x00ffffff-no-rj",
    date:"Jul 18, 2020",
    caption:"Vajpayee’s Story About A Nehru Portrait",
    vedio:"https://www.youtube.com/embed/EV3jGiSGRGA",
    comment:"In Parliament, I had my fair share of arguments with Nehru ji.This Atal Bihari Vajpayee speech was a throwback to the times when Indian politics was far less acrimonious.",
    },
    // {name:"",
    // logo:"",
    // date:"",
    // caption:"",
    // vedio:"",
    // comment:"",
    // },
];